config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do

  #############
  # 1 - Admin
  #############
  # ROOT
  root "static#home"
  
  # Rails admin
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :admins
  
  # Sidekiq 
  authenticate :admin do
    mount Sidekiq::Web => "/sidekiq"
  end
  
  # Token confirmation email 
  get '/:token/confirm_email/', :to => "subscribers#confirm_email", as: 'confirm_email'
  
  # 404
  get :url_not_found, :to => "static#url_not_found", :path => 'lien-perdu'
  
  #############
  # 2 - Core
  #############
  resources :subscribers, only: [] do 
    get '/activation/' => 'subscribers#activation'
    get :professionals, :path => 'nos-pros'
    get :email_validation, :path => 'validez-votre-email'
    get :email_confirmed, :path => 'confirmation'
    get '/research/edit' => 'subscriber_researches#edit'
    patch '/research/update' => 'subscriber_researches#update'
    get '/research/stop' => 'subscriber_researches#stop'
    get '/research/activate' => 'subscriber_researches#activate'
    get '/mon-financement' => 'subscribers#contact_courtier'
    post '/financement-submit' => 'subscribers#contact_courtier_submit'
    get '/mon-financement-confirmation' => 'subscribers#contact_courtier_submitted'
  end 
  
  
  resources :properties, only: [:show]
  
  
  resource :subscriber_researches do
    get :step1, :path => 'agglomeration'
    get :step2, :path => 'criteres'
    get :step3, :path => 'profil'
    post :validate_step
  end
  
  # Broker custom client inscription path
  get '/inscription/courtier/:broker_id' => "subscribers#broker_onboarding"
  
  #############
  # 4 - Dashboard
  #############
  get "/dashboard/" => "static_pages#dashboard"
  get "/dashboard/properties" => "static_pages#properties"
  get "/dashboard/stats" => "static_pages#stats"
  get "/dashboard/chart" => "static_pages#chart"
  get "/dashboard/price" => "static_pages#property_price"
  get "/dashboard/source" => "static_pages#sources"
  get "/dashboard/duplicates" => "static_pages#duplicates"
  get "/dashboard/courtiers/:year/:month" => "static_pages#general_broker_dashboard"
  get "/dashboard/courtiers/:broker_id" => "static_pages#broker_agency_dashboard"
  get "/dashboard/agglomerations/" => "static_pages#agglomerations_dashboard"
  get "/dashboard/leads/" => "static_pages#handle_dd_courtage_lead"
  
  #############
  # 5 - API
  #############  
  api_guard_scope 'subscribers' do
    post 'api/v1/subscribers/sign_up' => 'subscribers/registration#create'
    post 'api/v1/subscribers/sign_in' => 'subscribers/authentication#create'
    delete 'api/v1/subscribers/sign_out' => 'api_guard/authentication#destroy'
  end

  api_guard_scope 'brokers' do
    post 'api/v1/brokers/sign_in' => 'subscribers/authentication#create'
    delete 'api/v1/brokers/sign_out' => 'api_guard/authentication#destroy'
  end
  
  namespace "api" do
    namespace "v1" do
      
      # Dashboard Subscriber
      get '/subscribers/current' => "subscribers_dashboard#current" 
      get '/subscribers/properties' => "subscribers_dashboard#research_properties" 
      put '/subscribers/update' => 'subscribers_dashboard#update'
      post "/subscribers/loan/simulation" => "subscribers_dashboard#loan_simulation"
      get "/ads/:ads_id" => "subscribers_dashboard#get_property_details"
      post "/subscribers/note" => "subscribers_dashboard#create_subscriber_note"
      
      # Dashboard Courtier
      get '/brokers/current' => "brokers_dashboard#current" 
      put "/nuxt/subscribers/:subscriber_id" => "brokers_dashboard#update_subscriber"

      # Subscribers
      get "/subscribers/fb/:facebook_id" => "subscribers#show_facebook_id"
      post "/subscribers/fb/:facebook_id" => "subscribers#create_from_facebook_id"
      resources :subscribers do
        get "/get/props/last/:x/days" => "subscribers#props_x_days"
        get "/handle-onboarding" => "subscribers#handle_onboarding"
      end
      
      
      # Other models
      resources :researches, only: [:show, :update, :index, :destroy, :create]
      resources :properties, only: [:show, :index]
      resources :brokers, only: [:show]
      resources :notaries, only: [:show]
      resources :contractors, only: [:show]
      resources :subscriber_notes, only: [:create]
      resources :saved_properties, only: [:create, :destroy]

      # Nuxt 

      ## Broker Dashboards
      # get "/nuxt/brokers/:id/leads" => "nuxt#get_dashboard_leads"
      # put "/nuxt/subscribers/:id" => "nuxt#update_subscriber"
      

      # Auth token  
      get "/nuxt/subscribers/:auth_token" => "nuxt#get_subscriber"
      
      # Poubelle 
      get "/nuxt/brokers/:broker_id" => "nuxt#get_broker" #a priori plus utilisée
      post 'nuxt/funding/:subscriber_id/notify-broker' => 'nuxt#new_meeting_notify_broker' #plus utilisée
      get "/nuxt/researches/:research_id" => "nuxt#get_research"  #a priori plus utilisée

      # Onboarding users 
      get "/nuxt/areas" => "nuxt#get_available_areas"
      post "/nuxt/onboarding" => "nuxt#handle_onboarding"
      get "/nuxt/find/subscribers" => "nuxt#is_subscriber_exists?"
      get "/nuxt/subscribers/verify/:subscriber_token" => "nuxt#verify_email_subscriber"
      post "/nuxt/indicator/" => "nuxt#get_estimation"
      
      
      # Manychat 
      post "/manychat/s/:subscriber_id/update" => "manychat#update_subscriber"
      get "/manychat/s/:subscriber_id/send/props/morning" => "manychat#send_props_morning" 
      get "/manychat/s/:subscriber_id/send/props/favorites" => "manychat#send_props_favorites" 
      get "/manychat/s/:subscriber_id/send/last/:x/props" => "manychat#send_x_last_props"
      post "/manychat/s/:subscriber_id/add_status" => "manychat#create_subscriber_status" 
      get "/manychat/s/:subscriber_id/send/props/:property_id/details" => "manychat#send_prop_details" 
      get "/manychat/s/:subscriber_id/send/props/last/:x/days" => "manychat#send_props_x_days" 
      post "/manychat/s/:subscriber_id/loan/simulation" => "manychat#loan_simulation" 
      
      # Trello
      post "/trello/add_action" => "trello#add_action_to_broker" #a garder
      
      # Webhooks 
      post "webhooks/postmark/inbound" => "webhooks#handle_postmark_inbound"
      post "webhooks/postmark/growth-new-contact" => "webhooks#handle_postmark_new_contact"
      
      #data
      get "data/subscribers" => "data#get_subscribers"
      get "data/subscribers/active" => "data#get_active_subscribers"
      get "data/subscribers/facebook" => "data#get_facebook_id_subscribers"
    end
  end
  
  #############
  # 6 - Broker Dashboard
  #############
  
  get "/courtier/dashboard" => "broker_pages#index", :as => :broker_root
  post "/broker/checked" => "broker_pages#checked_by_broker"

   # Broker Authentificatgion 
   devise_for :brokers, controllers: {sessions: 'sessions'}
   devise_scope :broker do
     get 'brokers/current', to: 'sessions#show'
   end
 
   post '/sessions', to: "sessions#create"
 
end

app/controllers/subscriber_researches_controller.rb
class SubscriberResearchesController < ApplicationController
  before_action :load_subscriber_research_wizard, except: [:edit, :update, :validate_step, :stop, :activate]

  def validate_step
    current_step = params[:current_step]
    @subscriber_research_wizard = wizard_subscriber_research_for_step(current_step)
    @subscriber_research_wizard.subscriber_research.attributes = subscriber_research_wizard_params unless current_step == "step3"
    @subscriber_research_wizard.attributes = subscriber_wizard_params if current_step == "step3"
    session[:subscriber_research_attributes] = @subscriber_research_wizard.subscriber_research.attributes
    session[:subscriber_attributes] = @subscriber_research_wizard.subscriber.attributes
    ## Need to keep this params for research_area. Stored it in session.
    session[:areas] = params[:areas] unless params[:areas].nil?
    if @subscriber_research_wizard.valid?
      next_step = wizard_subscriber_research_next_step(current_step)
      create and return unless next_step

      redirect_to action: next_step
    else
      flash.now[:danger] = "Une erreur s'est produite, veuillez réessayer."
      render current_step
    end
  end

  def step1
    session[:areas] = [] #Reboot areas in case user changes agglomeration
    @agglomerations_infos = Agglomeration.where(is_active: true)
  end

  def step2
    session[:areas] = [] if session[:areas].nil?
    @master_areas = Area.selected_area_onboarding(@subscriber_research_wizard.agglomeration_id, session[:areas])
  end
  
  def step3
    if session[:areas].nil?
      flash.now[:danger] = "Veuillez sélectionner une zone de recherche."
      redirect_to step2_subscriber_researches_path
    end
  end

  def create
    subscriber_lead = Subscriber.find_by(email: @subscriber_research_wizard.subscriber.email, status: "new_lead")
    if subscriber_lead.nil?
      save_subscriber = @subscriber_research_wizard.subscriber.save(context: :onboarding)
      subscriber =  @subscriber_research_wizard.subscriber
    else
      save_subscriber =  subscriber_lead.update_attributes(firstname: @subscriber_research_wizard.subscriber.firstname, lastname: @subscriber_research_wizard.subscriber.lastname, phone: @subscriber_research_wizard.subscriber.phone, messenger_flux: @subscriber_research_wizard.subscriber.messenger_flux, email_flux: @subscriber_research_wizard.subscriber.email_flux, status: "")
      subscriber = subscriber_lead
    end
    # save_subscriber = subscriber_lead.nil? ? @subscriber_research_wizard.subscriber.save(context: :onboarding) : subscriber_lead.update_attributes(firstname:  @subscriber_research_wizard.subscriber.firstname, lastname:  @subscriber_research_wizard.subscriber.lastname, phone:  @subscriber_research_wizard.subscriber.phone, messenger_flux:  @subscriber_research_wizard.subscriber.messenger_flux, email_flux:  @subscriber_research_wizard.subscriber.email_flux, status:"")
    if save_subscriber
      subscriber.update(broker: Broker.find(session[:broker_id]), is_broker_affiliated: true) unless session[:broker_id].nil?
      @subscriber_research_wizard.subscriber_research.subscriber_id = subscriber.id
      if @subscriber_research_wizard.subscriber_research.save
        subscriber.handle_onboarding
        @subscriber_research_wizard.subscriber_research.update_research_areas(session[:areas])
        session[:subscriber_research_attributes] = nil
        session[:subscriber_attributes] = nil
        session[:areas] = nil 
        next_path = subscriber.email_flux && !subscriber.messenger_flux ? "#{ENV['BASE_URL']}subscribers/#{subscriber.id}/validez-votre-email" : "https://m.me/#{ENV['BOT_LINK']}?ref=id--#{subscriber.id}"
        redirect_to next_path, success: 'Votre alerte a été correctement créée!'
      else
        flash[:danger] = "Une erreur s'est produite, veuillez réessayer."
        redirect_to({ action: Wizard::SubscriberResearch::STEPS.second })
      end
    else 
      flash.now[:danger] = "Une erreur s'est produite, veuillez réessayer."
      render params[:current_step]
    end
  end

  def edit 
    # @subscriber = Subscriber.find(params[:subscriber_id])
    # @research = @subscriber.research
    # subscriber_areas_id = @research.areas.pluck(:id)
    # @master_areas = Area.selected_area_edit(@research.agglomeration_id, subscriber_areas_id)
    redirect_to "#{ENV['NUXT_URL']}/subscribers/account/criterias/edit"
  end

  def update
    @subscriber = Subscriber.find(params[:subscriber_id])
    @research = @subscriber.research
    areas_ids = []
    areas_ids += params[:areas] unless params[:areas].nil?
    if @research.update(research_params) && !areas_ids.empty?
      @research.update_research_areas(areas_ids)
      flash[:success] = "Les critères sont enregistrés ! Fermez cette fenêtre pour continuer."
    else
      flash[:danger] = "Sélectionnez des arrondissements..."
    end
    # // Send flow to subscriber
    if @subscriber.messenger_flux
      flow = "content20200914131931_703524"
      Manychat.new.send_flow_sequence(@subscriber, flow) unless Rails.env.development?
    end
    redirect_to subscriber_research_edit_path(@subscriber)
  end


  def stop
    # begin
    #   @confirmation = false
    #   @subscriber = Subscriber.find(params[:subscriber_id])
    #   if @subscriber.update(is_active: false)
    #     @subscriber.update(has_stopped: true, has_stopped_at: Time.now)
    #     SubscriberNote.create(subscriber: @subscriber, content:"L'utilisateur a arrêté son alerte.")
    #     AdminMailer.subscriber_email_stop(@subscriber.id).deliver_now
    #     @confirmation = true
    #   end
    # rescue ActiveRecord::RecordNotFound
    #   redirect_to root_path
    # end
    redirect_to "#{ENV['NUXT_URL']}/subscribers/account/profile/edit"
  end

  def activate 
    begin
      @confirmation = false
      @subscriber = Subscriber.find(params[:subscriber_id])
      if @subscriber.update(is_active: true)
        @subscriber.update(has_stopped: false, has_stopped_at: nil)
        SubscriberNote.create(subscriber: @subscriber, content:"L'utilisateur a reactivé son alerte.")
        AdminMailer.subscriber_email_reactivation(@subscriber.id).deliver_now
        @confirmation = true
      end
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
    end
  end

  private

  def load_subscriber_research_wizard
    @subscriber_research_wizard = wizard_subscriber_research_for_step(action_name)
  end

  def wizard_subscriber_research_next_step(step)
    Wizard::SubscriberResearch::STEPS[Wizard::SubscriberResearch::STEPS.index(step) + 1]
  end

  def wizard_subscriber_research_for_step(step)
    raise InvalidStep unless step.in?(Wizard::SubscriberResearch::STEPS)
    "Wizard::SubscriberResearch::#{step.camelize}".constantize.new(session[:subscriber_research_attributes], session[:subscriber_attributes])
  end

  def subscriber_research_wizard_params
    params.require(:subscriber_research_wizard).permit(:min_floor, :has_elevator, :min_elevator_floor, :min_surface, :min_rooms_number, :max_price, :min_price, :max_sqm_price, :balcony, :terrace, :garden, :new_construction, :last_floor, :home_type, :apartment_type, :agglomeration_id)
  end

  def subscriber_wizard_params
    params.require(:subscriber_wizard).permit(:subscriber_firstname, :subscriber_lastname, :subscriber_email, :subscriber_phone, :subscriber_messenger_flux, :subscriber_email_flux)
  end

  def research_params
    params.require(:research).permit(:min_floor, :has_elevator, :min_elevator_floor, :min_surface, :min_rooms_number, :max_price, :min_price, :max_sqm_price, :balcony, :terrace, :garden, :new_construction, :last_floor, :home_type, :apartment_type, :agglomeration_id)
  end

  class InvalidStep < StandardError; end
end

app/helpers/subscriber_researches_helper.rb
module SubscriberResearchesHelper
end

app/views/subscriber_researches/activate.html.erb
<div class="container">

    <div class="row mt-3"> 
        <div class="col d-flex justify-content-center"> 
            <img src="https://hellodingdong.com/assets/images/logo-ding-dong-full.png" class="mb-1 mr-2" style="height:30px">
        </div>
    </div>

<% if @confirmation%>

    <div class="row mt-4 mb-4">
        <div class="col-12">
            <h3 class="mb-3 grey_dark">
                <div class='text-center' style="font-family: 'Nunito'">Votre alerte est bien réactivée. </div>
            </h3> 
            <h5>
                <div class="mt-4 text-center"> 🏠 Vous recevrez à nouveau les annonces par mail 🏠 </div>
            </h5> 
            <div class="d-flex justify-content-center mt-5">
              <%= link_to "Arreter mon alerte", subscriber_research_stop_path, class: "btn medium-btn" %>
            </div>
        </div>
    </div>
    <div class="row mt-3 justify-content-center mt-5" style="margin-bottom:80px"> 
        <div class="col-12 col-lg-6 d-flex"> 
            <div class="d-flex justify-content-center" style="width:100%;height:0;padding-bottom:75%;position:relative;">
                <iframe src="https://giphy.com/embed/g9582DNuQppxC" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
            </div>
        </div>
    </div>

<% else %>
    <div class="row mt-4 mb-4">
        <div class="col-12">
            <h3 class="mb-3 grey_dark">
                <div class='text-center' style="font-family: 'Nunito'">Oups ! Une erreur s'est produite... </div>
            </h3> 
            <h5>
                <div class="mt-4 text-center"> 👨‍💻Revenez en arrière pour continuer 👨‍💻 </div>
            </h5> 
        </div>
    </div>
    <div class="row mt-3 justify-content-center mt-5" style="margin-bottom:80px"> 
        <div class="col-12 col-lg-6 d-flex"> 
            <div class="d-flex justify-content-center" style="width:100%;height:0;padding-bottom:75%;position:relative;">
                <iframe src="https://giphy.com/embed/3o7aCTPPm4OHfRLSH6" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
            </div>
        </div>
    </div>
<% end%>
  
</div>

<footer class="bg-dark text-white">
    <div class="separator-top">
        <div class="container py-5">
        <div class="row justify-content-between align-items-center">
            <div class="col-md-5 text-center text-md-left pl-2">

            <div>
                <small>793 337 643 RCS Paris</small>
            </div>
            <div>
                <small>Carte de Transaction : CPI75012017000018988</small>
            </div>
            <div>
                <small>Police d’assurance professionnelle : 41319158</small>
            </div>
            <div>
                <small>2020 © Ding Dong. Tous droits réservés.</small>
            </div>
            </div>
            <div class="col-md-2 text-center mt-4">
                <img class="logo-sm" src="https://hellodingdong.com/assets/images/logo-ding-dong-white.png" alt="Logo">
            </div>
        </div>
        </div>
    </div>
</footer>

app/views/subscriber_researches/edit.html.erb
<div class="row mt-3"> 
    <div class="col d-flex justify-content-center"> 
        <img src="https://hellodingdong.com/assets/images/logo-ding-dong-full.png" class="mb-1 mr-2" style="height:30px">
    </div>
</div>

<div class="container mb-100">


    <%= form_for @research, url: subscriber_research_update_path(@subscriber) do |f| %>

        <nav class="navbar navbar-light fixed-bottom bg-blue d-flex justify-content-center">
            <div class="d-flex justify-content-center mt-2 mb-2">
                <%= f.submit "Enregistrer mes critères 🚀",
                            class: "btn btn-outline-light",
                            style: "font-weight:600" %>
            </div>
        </nav>  



        <h5 class="mt-4 mb-3 grey_dark">Les critères indispensables pour commencer</h6> 

        <p class="mt-4 mb-3 grey">📍 Votre zone de recherche *</p>
        <div class="raw d-flex flex-wrap">
            <div class="form-group col-12 p-0 mb-0">
                <select multiple class="form-control" id="choices-multiple-remove-button" name="areas[]">
                  <% @master_areas.each do |item| %>
                    <% if item[0].include?("department") %>
                      <option value="<%= item[0] %>" <%= item[2] %>> <%= "#{item[1]}" %></option>
                    <% else %>
                      <option value="<%= item[0] %>" <%= item[3] %>> <%= "#{item[1]} (#{item[2]})" %></option>
                    <% end %>
                  <% end %>
                </select>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6 col-lg-4">
                <p class="mt-4 mb-3 grey">💰 Budget max *</p>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text input-group-text_style" id="basic-addon1">€</span>
                    </div>
                    <%= f.number_field :max_price, class: "form-control input_style", placeholder: "Ex : 500000", min: "10000", max: "10000000", :required => true %>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <p class="mt-4 mb-3 grey">↔️ Surface min *</p>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text input-group-text_style" id="basic-addon1">m2</span>
                    </div>
                    <%= f.number_field :min_surface, type: "number", class: "form-control input_style", placeholder: "Ex : 30", min: "8", max: "400", :required => true %>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <p class="mt-4 mb-3 grey">🏡 Nb. de pièces min *</p>
                <div class="input-group mb-3">
                    <%= f.number_field :min_rooms_number, class: "form-control input_style", placeholder: "Ex : 1", min: "1", max: "6", :required => true %>
                </div>
            </div>
        </div>



        <h5 class="mb-2 mt-4 grey_dark">Les critères optionnels pour affiner sa recherche</h6> 

        <div class="row">
            <div class="col-12 col-md-6 col-lg-4">
                <p class="mt-4 mb-3 grey"> 💰↘️ Budget min</p>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text input-group-text_style" id="basic-addon1">€</span>
                    </div>
                    <%= f.number_field :min_price, class: "form-control input_style", placeholder: "Ex : 0", :required => false %>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <p class="mt-4 mb-3 grey">💰↔️ Prix maximum au m2</p>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text input-group-text_style" id="basic-addon1">€ / m2</span>
                    </div>
                    <%= f.number_field :max_sqm_price, class: "form-control input_style", placeholder: "Ex : 12 000", :required => false %>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-6 col-lg-4">
                <p class="mt-4 mb-3 grey">🎢 Étage minimum</p>
                <div class="input-group mb-3">
                    <%= f.number_field :min_floor, class: "form-control input_style", placeholder: "Ex : 1 (pas de rez-de-chaussée)",  min: "0", max: "8" %>
                </div>
                <div class="form-check form-check-inline mb-3">
                <%= f.check_box :last_floor, class: "form-check-input", type:"checkbox",  id:"last_floor", value:"true" %> 
                <label class="form-check-label grey" for="last_floor">Uniquement dernier étage</label>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <p class="mt-4 mb-6 grey">🚠A partir de quel étage faut-il un ascenseur</p>
                <div class="input-group mb-3" style="margin-bottom:4.5rem">
                    <%= f.number_field :min_elevator_floor, class: "form-control input_style", placeholder: "Ex : 3 (ascenseur à partir du 3ème étage)", min: "0", max: "8" %>
                </div>
            </div>
        </div>
    
            <p class="mt-4 mb-6 grey">🏗️ Neuf</p>
            <div class="form-check form-check-inline">
                <%= f.check_box :new_construction, id: "new_construction", class: "form-check-input", checked: @research.new_construction %> 
                <%= f.label "Recevoir les constuctions neuves", for:"new_construction", class: "form-check-label grey" %> 
            </div>
            
            <p class="mt-4 mb-6 grey"> Souhaitez-vous une maison et/ou un appartement</p>
            <div class="form-check form-check-inline">
            <%= f.check_box :apartment_type, class: "form-check-input" %> 
            <%= f.label "Appartement", class: "form-check-label" %> 
            </div>
            <div class="form-check form-check-inline">
            <%= f.check_box :home_type, class: "form-check-input" %> 
            <%= f.label "Maison", class: "form-check-label" %> 
            </div>

            <% if false %>
            <p class="mt-4 mb-3" style="color: #0470C1; font-weight:400"> 🌻 Exterieur </p>
            <div class="form-check form-check-inline">
                <%= f.check_box :balcony, class: "form-check-input", type:"checkbox",  id:"balcony" %> 
                <label class="form-check-label" for="balcony">Balcon</label>
            </div>
            <div class="form-check form-check-inline">
                <%= f.check_box :terrace, class: "form-check-input", type:"checkbox",  id:"terrace" %> 
                <label class="form-check-label" for="terrace">Terrasse</label>
            </div>
            <div class="form-check form-check-inline">
                <%= f.check_box :garden, class: "form-check-input", type:"checkbox",  id:"garden" %> 
                <label class="form-check-label" for="garden">Jardin</label>
            </div>

            <% end %>
        </p>
        <% end %>

</div>


<script>
$(document).ready(function(){
        var multipleCancelButton = new Choices('#choices-multiple-remove-button', {
        removeItemButton: true,
        maxItemCount:100,
        searchResultLimit:100,
        renderChoiceLimit:100
        });
    });    
</script>
    
    

app/views/subscriber_researches/step1.html.erb
<div class="section bg-primary-pros" style="color: #2E60FF; font-family: 'Nunito'; font-size: 1rem;">

    <div class="container">

        <div class="row"> 
            <div class="col d-flex justify-content-center"> 
                <img src="<%= asset_path('logo_blanc.svg') %>" height="120px;" class="marginTopHeader">
            </div>
        </div>

        <div class="row marginTopSteps">
            <div class="col-12 display-flex mobileHide">
                <ul class="breadcrumb justify-content-center w-100 p-0" style="background: none">
                    <div class="col-4 text-center mb-1 p-0"><div class="badge-active"><%= link_to "1. Agglomération", step1_subscriber_researches_path, style:'color:#fff' %></div></div>
                    <div class="col-4 text-center mb-1 p-0"><div class="badge-off" >2. Critères</div></div>
                    <div class="col-4 text-center mb-1 p-0"><div class="badge-off">3. Compte</div></div>
                </ul>
            </div>
            <div class="col-12 display-flex mobileShow">
                <ul class="breadcrumb justify-content-center w-100 p-0" style="background: none">
                    <div class="col-4 text-center mb-1 p-0"><div class="badge-active"><%= link_to "1. Agglo.", step1_subscriber_researches_path, style:'color:#fff' %></div></div>
                    <div class="col-4 text-center mb-1 p-0"><div class="badge-off" >2. Crit.</div></div>
                    <div class="col-4 text-center mb-1 p-0"><div class="badge-off">3. Compte</div></div>
                </ul>
            </div>
        </div>

        <div class="bg-white-steps">
            <div class="container">
                <%= simple_form_for @subscriber_research_wizard, as: :subscriber_research_wizard, url: validate_step_subscriber_researches_path do |f| %>
                  <%= hidden_field_tag :current_step, 'step1' %>
                    <div class="container">
                        <div class="row mb-5 mt-5">
                            <div class="col-12 col-lg-6 mb-5 p-0">
                                <div class="mb-4 mt-lg-0">
                                    <div class="">
                                        <h5 class="mb-3">
                                            <div> Dans quelle agglomération cherchez-vous ?</div>
                                        </h5> 
                                    </div>
                                </div>
                                <div class="raw d-flex flex-wrap">
                                    <div class="form-group col-12 p-0 mb-0">
                                      <%= f.input_field :agglomeration_id, :collection => @agglomerations_infos.map{|o| [o.name, o.id, {disabled: !o.is_active}]},  class: "form-control", id: "choices-multiple-remove-button", label: false%>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-lg-6 display-flex justify-content-center margin-bottom-navbar mobileHide"> 
                                <img src="<%= asset_path('france-map.svg') %>" height="300px;">
                            </div>
                        </div>
                    </div>

                        <nav class="navbar navbar-light fixed-bottom navbarBlueLight">
                            <div class="container justify-content-center p-0">
                                <div class="row w-100 justify-content-center">
                                    <div class="col-12 col-md-6 col-lg-4 p-0">
                                        <%= f.submit "Etape suivante", class: "btn-outline-navbar w-75-mobile"%>
                                    </div>
                                </div>
                            </div>
                        </nav>  

                <%end%>

            </div>
        </div>
    </div>
</div>


<script>
$(document).ready(function(){
        var multipleCancelButton = new Choices('#choices-multiple-remove-button', {
        removeItemButton: true,
        maxItemCount:100,
        searchResultLimit:100,
        renderChoiceLimit:100
        });
    });    
function clearSelected(){
    var elements = document.getElementById("choices-multiple-remove-button").options;
     "<% session[:areas] = nil %>"
    for(var i = 0; i < elements.length; i++){
      elements[i].selected = false;
    }
  }
</script>