config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do

  #############
  # 1 - Admin
  #############
  # ROOT
  root "static#home"
  
  # Rails admin
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :admins
  
  # Sidekiq 
  authenticate :admin do
    mount Sidekiq::Web => "/sidekiq"
  end
  
  # Token confirmation email 
  get '/:token/confirm_email/', :to => "subscribers#confirm_email", as: 'confirm_email'
  
  # 404
  get :url_not_found, :to => "static#url_not_found", :path => 'lien-perdu'
  
  #############
  # 2 - Core
  #############
  resources :subscribers, only: [] do 
    get '/activation/' => 'subscribers#activation'
    get :professionals, :path => 'nos-pros'
    get :email_validation, :path => 'validez-votre-email'
    get :email_confirmed, :path => 'confirmation'
    get '/research/edit' => 'subscriber_researches#edit'
    patch '/research/update' => 'subscriber_researches#update'
    get '/research/stop' => 'subscriber_researches#stop'
    get '/research/activate' => 'subscriber_researches#activate'
    get '/mon-financement' => 'subscribers#contact_courtier'
    post '/financement-submit' => 'subscribers#contact_courtier_submit'
    get '/mon-financement-confirmation' => 'subscribers#contact_courtier_submitted'
  end 
  
  
  resources :properties, only: [:show]
  
  
  resource :subscriber_researches do
    get :step1, :path => 'agglomeration'
    get :step2, :path => 'criteres'
    get :step3, :path => 'profil'
    post :validate_step
  end
  
  # Broker custom client inscription path
  get '/inscription/courtier/:broker_id' => "subscribers#broker_onboarding"
  
  #############
  # 4 - Dashboard
  #############
  get "/dashboard/" => "static_pages#dashboard"
  get "/dashboard/properties" => "static_pages#properties"
  get "/dashboard/stats" => "static_pages#stats"
  get "/dashboard/chart" => "static_pages#chart"
  get "/dashboard/price" => "static_pages#property_price"
  get "/dashboard/source" => "static_pages#sources"
  get "/dashboard/duplicates" => "static_pages#duplicates"
  get "/dashboard/courtiers/:year/:month" => "static_pages#general_broker_dashboard"
  get "/dashboard/courtiers/:broker_id" => "static_pages#broker_agency_dashboard"
  get "/dashboard/agglomerations/" => "static_pages#agglomerations_dashboard"
  get "/dashboard/leads/" => "static_pages#handle_dd_courtage_lead"
  
  #############
  # 5 - API
  #############  
  api_guard_scope 'subscribers' do
    post 'api/v1/subscribers/sign_up' => 'subscribers/registration#create'
    post 'api/v1/subscribers/sign_in' => 'subscribers/authentication#create'
    delete 'api/v1/subscribers/sign_out' => 'api_guard/authentication#destroy'
  end

  api_guard_scope 'brokers' do
    post 'api/v1/brokers/sign_in' => 'subscribers/authentication#create'
    delete 'api/v1/brokers/sign_out' => 'api_guard/authentication#destroy'
  end
  
  namespace "api" do
    namespace "v1" do
      
      # Dashboard Subscriber
      get '/subscribers/current' => "subscribers_dashboard#current" 
      get '/subscribers/properties' => "subscribers_dashboard#research_properties" 
      put '/subscribers/update' => 'subscribers_dashboard#update'
      post "/subscribers/loan/simulation" => "subscribers_dashboard#loan_simulation"
      get "/ads/:ads_id" => "subscribers_dashboard#get_property_details"
      post "/subscribers/note" => "subscribers_dashboard#create_subscriber_note"
      
      # Dashboard Courtier
      get '/brokers/current' => "brokers_dashboard#current" 
      put "/nuxt/subscribers/:subscriber_id" => "brokers_dashboard#update_subscriber"

      # Subscribers
      get "/subscribers/fb/:facebook_id" => "subscribers#show_facebook_id"
      post "/subscribers/fb/:facebook_id" => "subscribers#create_from_facebook_id"
      resources :subscribers do
        get "/get/props/last/:x/days" => "subscribers#props_x_days"
        get "/handle-onboarding" => "subscribers#handle_onboarding"
      end
      
      
      # Other models
      resources :researches, only: [:show, :update, :index, :destroy, :create]
      resources :properties, only: [:show, :index]
      resources :brokers, only: [:show]
      resources :notaries, only: [:show]
      resources :contractors, only: [:show]
      resources :subscriber_notes, only: [:create]
      resources :saved_properties, only: [:create, :destroy]

      # Nuxt 

      ## Broker Dashboards
      # get "/nuxt/brokers/:id/leads" => "nuxt#get_dashboard_leads"
      # put "/nuxt/subscribers/:id" => "nuxt#update_subscriber"
      

      # Auth token  
      get "/nuxt/subscribers/:auth_token" => "nuxt#get_subscriber"
      
      # Poubelle 
      get "/nuxt/brokers/:broker_id" => "nuxt#get_broker" #a priori plus utilisée
      post 'nuxt/funding/:subscriber_id/notify-broker' => 'nuxt#new_meeting_notify_broker' #plus utilisée
      get "/nuxt/researches/:research_id" => "nuxt#get_research"  #a priori plus utilisée

      # Onboarding users 
      get "/nuxt/areas" => "nuxt#get_available_areas"
      post "/nuxt/onboarding" => "nuxt#handle_onboarding"
      get "/nuxt/find/subscribers" => "nuxt#is_subscriber_exists?"
      get "/nuxt/subscribers/verify/:subscriber_token" => "nuxt#verify_email_subscriber"
      post "/nuxt/indicator/" => "nuxt#get_estimation"
      
      
      # Manychat 
      post "/manychat/s/:subscriber_id/update" => "manychat#update_subscriber"
      get "/manychat/s/:subscriber_id/send/props/morning" => "manychat#send_props_morning" 
      get "/manychat/s/:subscriber_id/send/props/favorites" => "manychat#send_props_favorites" 
      get "/manychat/s/:subscriber_id/send/last/:x/props" => "manychat#send_x_last_props"
      post "/manychat/s/:subscriber_id/add_status" => "manychat#create_subscriber_status" 
      get "/manychat/s/:subscriber_id/send/props/:property_id/details" => "manychat#send_prop_details" 
      get "/manychat/s/:subscriber_id/send/props/last/:x/days" => "manychat#send_props_x_days" 
      post "/manychat/s/:subscriber_id/loan/simulation" => "manychat#loan_simulation" 
      
      # Trello
      post "/trello/add_action" => "trello#add_action_to_broker" #a garder
      
      # Webhooks 
      post "webhooks/postmark/inbound" => "webhooks#handle_postmark_inbound"
      post "webhooks/postmark/growth-new-contact" => "webhooks#handle_postmark_new_contact"
      
      #data
      get "data/subscribers" => "data#get_subscribers"
      get "data/subscribers/active" => "data#get_active_subscribers"
      get "data/subscribers/facebook" => "data#get_facebook_id_subscribers"
    end
  end
  
  #############
  # 6 - Broker Dashboard
  #############
  
  get "/courtier/dashboard" => "broker_pages#index", :as => :broker_root
  post "/broker/checked" => "broker_pages#checked_by_broker"

   # Broker Authentificatgion 
   devise_for :brokers, controllers: {sessions: 'sessions'}
   devise_scope :broker do
     get 'brokers/current', to: 'sessions#show'
   end
 
   post '/sessions', to: "sessions#create"
 
end

app/views/lead/create.html.erb
<h1>Création d'un nouveau contact</h1>

<%= form_for @lead, url: "/lead/new" do |f| %>
      
      <h4 class="mt-5">Identité</h4>
      <div class="row">
        <div class="col-6">
          <h5 class="mt-4 mb-3" style="color: #525f7f; font-weight:400">Prénom *</h5>
          <div class="input-group mb-3">
              <%= f.text_field :firstname, class: "form-control", placeholder:"Jean", :required => true   %>
          </div>
        </div>
        <div class="col-6">
          <h5 class="mt-4 mb-3" style="color: #525f7f; font-weight:400">Nom *</h5>
          <div class="input-group mb-3">
              <%= f.text_field :lastname, class: "form-control", placeholder:"Dupond", :required => true   %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-6">
          <h5 class="mt-4 mb-3" style="color: #525f7f; font-weight:400">Email *</h5>
          <div class="input-group mb-3">
              <%= f.email_field :email, class: "form-control", placeholder:"jean.dupond@gmail.com", :required => true   %>
          </div>
        </div>
        <div class="col-6">
          <h5 class="mt-4 mb-3" style="color: #525f7f; font-weight:400">Téléphone *</h5>
          <div class="input-group mb-3">
              <%= f.text_field :phone, class: "form-control", placeholder:"0783746253", :required => true   %>
          </div>
        </div>
      </div>


      <h4 class="mt-5">Projet immobilier</h4>
      <h5 class="mt-4 mb-3" style="color: #525f7f; font-weight:400"> Type de projet </h5>
      <div class="input-group mb-3">
          <%= f.select :project_type, options_for_select([["Chosir...", ""], "1er achat", "2e achat ou +", "Investissement Locatif", "Chasseur Immobilier"]), class: "form-control", placeholder:"A déjà parlé avec son banquier mais ...", rows:5, cols:5, :required => false   %>
      </div>

      <div class="row">
        <div class="col-4">
          <h5 class="mt-4 mb-3" style="color: #525f7f; font-weight:400">💰 Prix d'achat maximum ? *</h5>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">€</span>
            </div>
            <%= f.number_field :max_price, class: "form-control", placeholder:"Ex : 500000", min:"10000", max:"10000000", :required => true %>
        </div>
        </div>
        <div class="col-4">
          <h5 class="mt-4 mb-3" style="color: #525f7f; font-weight:400">↔️ Surface minimum ? *</h5>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">m2</span>
            </div>
            <%= f.number_field :min_surface, type:"number", class: "form-control", placeholder:"Ex : 30", min:"8", max:"400", :required => true   %>
        </div>
        </div>
        <div class="col-4">
          <h5 class="mt-4 mb-3" style="color: #525f7f; font-weight:400">🏡 Nombre de pièces minimum ? *</h5>
          <div class="input-group mb-3">
              <%= f.number_field :min_rooms_number, class: "form-control", placeholder:"Ex : 1", min:"1", max:"6", :required => true   %>
          </div>
        </div>
      </div>

      <h5 class="mb-3 mt-4" style="color: #525f7f; font-weight:400;">📍 Arrondissements ? *</h5>
      <div class="d-flex flex-wrap">
        <% @areas.each do |area| %>
          <div 
              class="form-check mr-3 <%=area.name%> d-flex" 
              onclick="changeColor(className)"
          >       <div>
                      <%= check_box_tag 'selected_area[]', 
                          area.id, 
                          false, 
                          class: "",
                          id: area.name
                      %>
                  </div>
                  <label class="form-check-label mb-2 ml-2" for="<%=area.name%>">
                      <%= area.name %>
                  </label>

          </div>
        <% end %>
      </div>

        <h5 class="mt-4 mb-3" style="color: #525f7f; font-weight:400"> Critères spécifiques </h5>
        <div class="input-group mb-3">
            <%= f.text_area :specific_criteria, class: "form-control", placeholder:"Avec vue dégagée sur la Tour Eiffel ...", rows:5, cols:5, :required => false   %>
        </div>

        <h5 class="mt-4 mb-3" style="color: #525f7f; font-weight:400"> Remarques supplémentaires </h5>
        <div class="input-group mb-3">
            <%= f.text_area :additional_question, class: "form-control", placeholder:"A déjà parlé avec son banquier mais ...", rows:5, cols:5, :required => false   %>
        </div>

        <h4 class="mt-5">Ding Dong</h4>
        
        <div class="row"  style="margin-bottom:100px;">
        <div class="col-6">
          <h5 class="mt-4 mb-3" style="color: #525f7f; font-weight:400"> Courtier Ding Dong de référence *</h5>
        <div class="input-group mb-3">
            <%= f.select :project_type, options_for_select(@broker_select), class: "form-control", :required => true   %>
        </div>
        </div>
        <div class="col-6">
          <h5 class="mt-4 mb-3" style="color: #525f7f; font-weight:400">Source du lead</h5>
          <div class="input-group mb-3">
              <%= f.text_field :lastname, class: "form-control", placeholder:"Folhomee, réseau interne, ...", :required => false   %>
          </div>
        </div>
      </div>

      <nav class="navbar navbar-light fixed-bottom bg-primary d-flex justify-content-center">
        <div class="d-flex justify-content-center mt-2 mb-2">
            <%= f.submit "Créer le contact 🚀", 
                class: "btn btn-outline-light", 
                style:"font-weight:600"
            %>
        </div>
      </nav>

       

        <div class="d-flex justify-content-center mt-4 mb-6">
        -------- 🔔--------
        </div>
      </p>
    <% end %>

app/views/lead/onboarding.html.erb
    <h4 class="text-center mt-5" style="color: #525f7f; font-weight:400">Bienvenue chez Ding Dong !</h4>

    <div class="d-flex justify-content-center mt-5" style="background:white">
        <img style="width: 100%; max-width: 700px;" src="https://media-private.canva.com/oYO_U/MAD6WYoYO_U/1/s.jpg?response-expires=Fri%2C%2024%20Apr%202020%2012%3A28%3A05%20GMT&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200424T093729Z&X-Amz-SignedHeaders=host&X-Amz-Expires=10235&X-Amz-Credential=AKIAJWF6QO3UH4PAAJ6Q%2F20200424%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=3f2a1bedf69f886937c885a01b910877cf52105170512e1df83d94306bbc1a90" alt="Equipe Ding Dong"><img>
    </div>

    <h5 class="text-center mt-5" style="color: #525f7f; font-weight:400">Voici quelques questions pour mieux cerner ton projet d'achat 🙂</h5>

    <div class="d-flex justify-content-center align-items-center mt-2">
        <img style="width: 40px;" class="mr-2" src="https://media-private.canva.com/wEYrU/MAD1xrwEYrU/1/s.png?response-expires=Fri%2C%2024%20Apr%202020%2012%3A57%3A53%20GMT&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200424T100524Z&X-Amz-SignedHeaders=host&X-Amz-Expires=10348&X-Amz-Credential=AKIAJJATJK7JCUD446NA%2F20200424%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=67d03d6ac48f71405d2d1803a15926a6d8607bbc7da5195d7c86093dbf4799e0" alt="Equipe Ding Dong"><img>
        <h5 class="text-center mb-0" style="color: #525f7f; font-weight:400">
            30 sec chrono !
        </h5>
    </div>

    <div class="row">
        <div class="col-12 col-md-6">
            <h5 class="mt-5 mb-3" style="color: #525f7f; font-weight:400">🔎 Où recherches-tu ? *</h5>
                <%= form_tag(new_lead_path, :id => 'zone_selection_form', method: :get) do |f| %>

                <div class="d-flex flex-wrap">
                    <% @zone_select.each do |zone| %>
                    <div>
                        <div class="d-flex justify-content-center align-items-center mt-2 mb-2">
                        <% if zone == "Paris" %>
                            <img style="width: 80px;" class="mr-2" src="https://media-private.canva.com/-sB-4/MAD1wu-sB-4/1/s.png?response-expires=Fri%2C%2024%20Apr%202020%2012%3A29%3A06%20GMT&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200424T100547Z&X-Amz-SignedHeaders=host&X-Amz-Expires=8598&X-Amz-Credential=AKIAJJATJK7JCUD446NA%2F20200424%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=588abd26b40a556ae4f20d404bf50902e7eeaf5c0bed175a847886122a0d14b2" alt="Equipe Ding Dong"><img>
                        <% elsif zone == "Banlieue-Ouest" %>
                            <img style="width: 80px;" class="mr-2" src="https://media-private.canva.com/sItjo/MAD6W8sItjo/1/s.png?response-expires=Fri%2C%2024%20Apr%202020%2013%3A48%3A32%20GMT&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200424T113047Z&X-Amz-SignedHeaders=host&X-Amz-Expires=8264&X-Amz-Credential=AKIAJWF6QO3UH4PAAJ6Q%2F20200424%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=7a90793ba9e2fca73cd87bed8e44eae6416d050dd18eeae7b3a1df97861616d7" alt="Equipe Ding Dong"><img>
                        <% end %>
                        </div>
                        <div 
                            class="form-check mr-3 <%=zone%> d-flex" 
                            style="font-size: 1em;
                                border: solid 1px;
                                border-color:white;
                                padding: 5px 10px 0px 10px;
                                background: #e9ecef;
                                color: #525f7f;
                                border-radius: 36px;" 
                            onclick="changeColor(className)"
                        >       <div>
                                    <%= check_box_tag 'selected_zones[]', 
                                        zone, 
                                        false, 
                                        class: "",
                                        id: zone
                                    %>
                                </div>
                                <label class="form-check-label mb-2 ml-2" for="<%=zone%>">
                                    <%= zone %>
                                </label>

                        </div>
                    </div>
                    <% end %>
                </div>
                <nav class="navbar navbar-light fixed-bottom bg-primary d-flex justify-content-center">
                    <div class="d-flex justify-content-center mt-2 mb-2">
                        <%= submit_tag "C'est parti ! 🚀", :name => 'commit', class: "btn btn-outline-light", style:"font-weight:600" %>
                    </div>
                </nav>
                <% end %>
            <div class="mt-5 mb-6">
            </div>
            <br><br>
        </div>
    </div>



<script>
    
    function changeColor(className) {
      let item = document.getElementsByClassName(className)[0]
      let label = item.children[1]
      let checkboxValue = item.children[0].children[0].checked
      console.log(item)
    
      if(checkboxValue){ 
          item.style.backgroundColor = "#57b894"
          label.style.color = "white"
        }
      else{
          item.style.backgroundColor = "#e9ecef"
          label.style.color = "#525f7f"
        }
    }


    function selectAll(className) {
        let all_items = document.getElementsByClassName(className)

        if(all_items[0].checked){
            for(i=1; i < 21; i++){
                all_items[i].checked = true;
                all_items[i].parentNode.nextElementSibling.style.color = "#57b894"
            }
        }
        else{
            for(i=1; i < 21; i++){
                all_items[i].checked = false;
                all_items[i].parentNode.nextElementSibling.style.color = "black"
            }
        }
    }


</script>