config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do

  #############
  # 1 - Admin
  #############
  # ROOT
  root "static#home"
  
  # Rails admin
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :admins
  
  # Sidekiq 
  authenticate :admin do
    mount Sidekiq::Web => "/sidekiq"
  end
  
  # Token confirmation email 
  get '/:token/confirm_email/', :to => "subscribers#confirm_email", as: 'confirm_email'
  
  # 404
  get :url_not_found, :to => "static#url_not_found", :path => 'lien-perdu'
  
  #############
  # 2 - Core
  #############
  resources :subscribers, only: [] do 
    get '/activation/' => 'subscribers#activation'
    get :professionals, :path => 'nos-pros'
    get :email_validation, :path => 'validez-votre-email'
    get :email_confirmed, :path => 'confirmation'
    get '/research/edit' => 'subscriber_researches#edit'
    patch '/research/update' => 'subscriber_researches#update'
    get '/research/stop' => 'subscriber_researches#stop'
    get '/research/activate' => 'subscriber_researches#activate'
    get '/mon-financement' => 'subscribers#contact_courtier'
    post '/financement-submit' => 'subscribers#contact_courtier_submit'
    get '/mon-financement-confirmation' => 'subscribers#contact_courtier_submitted'
  end 
  
  
  resources :properties, only: [:show]
  
  
  resource :subscriber_researches do
    get :step1, :path => 'agglomeration'
    get :step2, :path => 'criteres'
    get :step3, :path => 'profil'
    post :validate_step
  end
  
  # Broker custom client inscription path
  get '/inscription/courtier/:broker_id' => "subscribers#broker_onboarding"
  
  #############
  # 4 - Dashboard
  #############
  get "/dashboard/" => "static_pages#dashboard"
  get "/dashboard/properties" => "static_pages#properties"
  get "/dashboard/stats" => "static_pages#stats"
  get "/dashboard/chart" => "static_pages#chart"
  get "/dashboard/price" => "static_pages#property_price"
  get "/dashboard/source" => "static_pages#sources"
  get "/dashboard/duplicates" => "static_pages#duplicates"
  get "/dashboard/courtiers/:year/:month" => "static_pages#general_broker_dashboard"
  get "/dashboard/courtiers/:broker_id" => "static_pages#broker_agency_dashboard"
  get "/dashboard/agglomerations/" => "static_pages#agglomerations_dashboard"
  get "/dashboard/leads/" => "static_pages#handle_dd_courtage_lead"
  
  #############
  # 5 - API
  #############  
  api_guard_scope 'subscribers' do
    post 'api/v1/subscribers/sign_up' => 'subscribers/registration#create'
    post 'api/v1/subscribers/sign_in' => 'subscribers/authentication#create'
    delete 'api/v1/subscribers/sign_out' => 'api_guard/authentication#destroy'
  end

  api_guard_scope 'brokers' do
    post 'api/v1/brokers/sign_in' => 'subscribers/authentication#create'
    delete 'api/v1/brokers/sign_out' => 'api_guard/authentication#destroy'
  end
  
  namespace "api" do
    namespace "v1" do
      
      # Dashboard Subscriber
      get '/subscribers/current' => "subscribers_dashboard#current" 
      get '/subscribers/properties' => "subscribers_dashboard#research_properties" 
      put '/subscribers/update' => 'subscribers_dashboard#update'
      post "/subscribers/loan/simulation" => "subscribers_dashboard#loan_simulation"
      get "/ads/:ads_id" => "subscribers_dashboard#get_property_details"
      post "/subscribers/note" => "subscribers_dashboard#create_subscriber_note"
      
      # Dashboard Courtier
      get '/brokers/current' => "brokers_dashboard#current" 
      put "/nuxt/subscribers/:subscriber_id" => "brokers_dashboard#update_subscriber"

      # Subscribers
      get "/subscribers/fb/:facebook_id" => "subscribers#show_facebook_id"
      post "/subscribers/fb/:facebook_id" => "subscribers#create_from_facebook_id"
      resources :subscribers do
        get "/get/props/last/:x/days" => "subscribers#props_x_days"
        get "/handle-onboarding" => "subscribers#handle_onboarding"
      end
      
      
      # Other models
      resources :researches, only: [:show, :update, :index, :destroy, :create]
      resources :properties, only: [:show, :index]
      resources :brokers, only: [:show]
      resources :notaries, only: [:show]
      resources :contractors, only: [:show]
      resources :subscriber_notes, only: [:create]
      resources :saved_properties, only: [:create, :destroy]

      # Nuxt 

      ## Broker Dashboards
      # get "/nuxt/brokers/:id/leads" => "nuxt#get_dashboard_leads"
      # put "/nuxt/subscribers/:id" => "nuxt#update_subscriber"
      

      # Auth token  
      get "/nuxt/subscribers/:auth_token" => "nuxt#get_subscriber"
      
      # Poubelle 
      get "/nuxt/brokers/:broker_id" => "nuxt#get_broker" #a priori plus utilisée
      post 'nuxt/funding/:subscriber_id/notify-broker' => 'nuxt#new_meeting_notify_broker' #plus utilisée
      get "/nuxt/researches/:research_id" => "nuxt#get_research"  #a priori plus utilisée

      # Onboarding users 
      get "/nuxt/areas" => "nuxt#get_available_areas"
      post "/nuxt/onboarding" => "nuxt#handle_onboarding"
      get "/nuxt/find/subscribers" => "nuxt#is_subscriber_exists?"
      get "/nuxt/subscribers/verify/:subscriber_token" => "nuxt#verify_email_subscriber"
      post "/nuxt/indicator/" => "nuxt#get_estimation"
      
      
      # Manychat 
      post "/manychat/s/:subscriber_id/update" => "manychat#update_subscriber"
      get "/manychat/s/:subscriber_id/send/props/morning" => "manychat#send_props_morning" 
      get "/manychat/s/:subscriber_id/send/props/favorites" => "manychat#send_props_favorites" 
      get "/manychat/s/:subscriber_id/send/last/:x/props" => "manychat#send_x_last_props"
      post "/manychat/s/:subscriber_id/add_status" => "manychat#create_subscriber_status" 
      get "/manychat/s/:subscriber_id/send/props/:property_id/details" => "manychat#send_prop_details" 
      get "/manychat/s/:subscriber_id/send/props/last/:x/days" => "manychat#send_props_x_days" 
      post "/manychat/s/:subscriber_id/loan/simulation" => "manychat#loan_simulation" 
      
      # Trello
      post "/trello/add_action" => "trello#add_action_to_broker" #a garder
      
      # Webhooks 
      post "webhooks/postmark/inbound" => "webhooks#handle_postmark_inbound"
      post "webhooks/postmark/growth-new-contact" => "webhooks#handle_postmark_new_contact"
      
      #data
      get "data/subscribers" => "data#get_subscribers"
      get "data/subscribers/active" => "data#get_active_subscribers"
      get "data/subscribers/facebook" => "data#get_facebook_id_subscribers"
    end
  end
  
  #############
  # 6 - Broker Dashboard
  #############
  
  get "/courtier/dashboard" => "broker_pages#index", :as => :broker_root
  post "/broker/checked" => "broker_pages#checked_by_broker"

   # Broker Authentificatgion 
   devise_for :brokers, controllers: {sessions: 'sessions'}
   devise_scope :broker do
     get 'brokers/current', to: 'sessions#show'
   end
 
   post '/sessions', to: "sessions#create"
 
end

app/controllers/api/v1/subscribers_controller.rb
require 'dotenv/load'

class Api::V1::SubscribersController < ActionController::API
    include ActionController::HttpAuthentication::Token::ControllerMethods

    TOKEN = ENV['BEARER_TOKEN']
    before_action :authentificate


    # GET /subscribers
    def index
        @subscribers = Subscriber.all
        render json: {status: 'SUCCESS', message: 'List of all users', data: @subscribers}, status: 200
    end

    # GET /subscribers/:id
    def show
        begin
            subscriber = Subscriber.find(params[:id])
            data = subscriber.as_json
            data[:areas_list] = subscriber.get_areas_list
            data[:edit_path] = subscriber.get_edit_path
            data[:research_id] = subscriber.research.id
            render json: {status: 'SUCCESS', message: 'Required subscriber', data: data}, status: 200
        rescue ActiveRecord::RecordNotFound
            render json: {status: 'ERROR', message: 'Subscriber not found', data: nil}, status: 404
        end
    end

    # POST /subscribers/
    def create 
        sub = Subscriber.new(subscriber_params)
        if sub.save
            render json: {status: 'SUCCESS', message: 'Subscriber created', data: sub}, status: 200
        else
            render json: {status: 'ERROR', message: 'Subscriber could not be created', data: sub.errors}, status: 500
        end
    end

    # PUT /subscribers/:id
    def update 
        begin
            @subscriber = Subscriber.find(params[:id])
            @subscriber.update(subscriber_params)
            render json: {status: 'SUCCESS', message: 'Subscriber updated', data: @subscriber}, status: 200
        rescue ActiveRecord::RecordNotFound
            render json: {status: 'ERROR', message: 'Subscriber not found', data: nil}, status: 404
        end
    end

     # DELETE /subscribers/:id
     def destroy 
        begin
            @subscriber = Subscriber.find(params[:id])
            @subscriber.destroy
            render json: {status: 'SUCCESS', message: 'Subscriber deleted', data: @subscriber}, status: 200
        rescue ActiveRecord::RecordNotFound
            render json: {status: 'ERROR', message: 'Subscriber not found', data: nil}, status: 404
        end
    end

    # GET /subscribers/fb/:facebook_id
    def show_facebook_id
        @subscriber = Subscriber.where(facebook_id: params[:facebook_id]).first
        if  !@subscriber.nil?
            render json: {status: 'SUCCESS', message: 'Required subscriber', data: @subscriber}, status: 200
        else
            render json: {status: 'ERROR', message: 'Subscriber not found', data: nil}, status: 404
        end
    end

    # POST /suscribers/fb/:facebook_id
    def create_from_facebook_id
        # sub  = Subscriber.find_by(facebook_id: params[:facebook_id])
        # @subscriber = sub.nil? ? Subscriber.new(facebook_id: params[:facebook_id]) : sub
        @subscriber = Subscriber.new(facebook_id: params[:facebook_id]) 
        if @subscriber.save(context: :facebook_creation)
            data = @subscriber.as_json
            data[:edit_path] = @subscriber.get_edit_path
            render json: {status: 'SUCCESS', message: 'Subscriber created', data: data}, status: 200
        else
            render json: {status: 'ERROR', message: 'Subscriber could not be created', data: @subscriber.errors}, status: 500
        end

    end

    # GET /subscribers/:subscriber_id/handle-onboarding 
    def handle_onboarding
        Subscriber.find(params[:subscriber_id]).handle_onboarding
        render json: {status: 'SUCCESS', message: 'Subscriber onboarded', data: Subscriber.find(params[:subscriber_id])}, status: 200
    end


    private

    def subscriber_params
        params.permit(:firstname, :lastname, :email, :phone, :facebook_id, :is_active, :max_price, :min_surface, :trello_id_card, :broker_id, :hot_lead, :status)
    end

    def authentificate
        authenticate_or_request_with_http_token do |token, options|
            ActiveSupport::SecurityUtils.secure_compare(token, TOKEN)
        end
    end
end

app/controllers/subscribers/authentication_controller.rb
module Subscribers
  class AuthenticationController < ApiGuard::AuthenticationController
    # before_action :find_resource, only: [:create]
    # before_action :authenticate_resource, only: [:destroy]

    def create
      if subscriber = resource ?  resource.authenticate(params[:password]) : Subscriber.get_by_auth_token(params[:auth_token])
        create_token_and_set_header(subscriber, resource_name)
        render json: {message: I18n.t('api_guard.authentication.signed_in'), token: response.header["Access-Token"] }, status: 200
      else
        render_error(422, message: I18n.t('api_guard.authentication.invalid_login_credentials'))
      end
    end

    # def destroy
    #   blacklist_token
    #   render_success(message: I18n.t('api_guard.authentication.signed_out'))
    # end

    private

    def find_resource
      self.resource = resource_class.where(email: params[:email].downcase.strip).last if params[:email].present?
      render_error(422, message: I18n.t('api_guard.authentication.invalid_login_credentials')) unless (resource || !resource && params[:auth_token].present?)
    end
  end
end

app/controllers/subscribers/registration_controller.rb
module Subscribers
  class RegistrationController < ApiGuard::RegistrationController
    # before_action :authenticate_resource, only: [:destroy]

    def create
      resource = Subscriber.where(email: params[:email].downcase.strip).last
      resource.nil? ? resource = init_resource(sign_up_params) : resource.password_digest = init_resource(sign_up_params).password_digest
      if resource.save
        create_token_and_set_header(resource, resource_name)
        render_success(message: I18n.t('api_guard.registration.signed_up'))
      else
        render_error(422, object: resource)
      end
    end

    # def destroy
    #   current_resource.destroy
    #   render_success(message: I18n.t('api_guard.registration.account_deleted'))
    # end

    private

    def sign_up_params
      params.require(:registration).permit(:email, :password, :password_confirmation)
    end
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController  

  
  # #########################
  #      BUSINESS LOGIC     #
  # #########################

  def professionals
    @subscriber = Subscriber.find(params[:subscriber_id])
    @notary = @subscriber.notary
    @broker = @subscriber.broker
    @contractor = @subscriber.contractor
  end
  
  def activation
    flow = "content20200716090652_490399"
    @subscriber = Subscriber.find(params[:subscriber_id])
    if !@subscriber.nil?
      @subscriber.update(is_blocked: false) 
      SubscriberStatus.create(subscriber: @subscriber, status: Status.find_by(name: "unblocked"))
      Manychat.new.send_flow_sequence(@subscriber, flow)
    end
  end

  def confirm_email
    subscriber = Subscriber.find_by_confirm_token(params[:token])
    if subscriber
      subscriber.validate_email
      subscriber.save(validate: true)
      SubscriberMailer.welcome_email(subscriber).deliver_now
      redirect_to subscriber_email_confirmed_path(subscriber)
    else
      flash[:error] = "Désolé, l'utilisateur n'existe pas"
      redirect_to url_not_found_path
    end
  end

  def email_validation
    @subscriber = Subscriber.find(params[:subscriber_id])
  end

  def email_confirmed
    subscriber = Subscriber.find(params[:subscriber_id])
    redirect_to root_path if subscriber.messenger_flux || !subscriber 
  end

  def broker_onboarding
    session[:broker_id] = params[:broker_id]
    redirect_to step1_subscriber_researches_path
  end

  def contact_courtier
    @subscriber = Subscriber.find(params[:subscriber_id])
    @question_categories = ["Evaluer ma capacité d'emprunt", "Informations sur les taux", "Parler à un courtier", "Point sur ma situation" ,"Autre"]
    SubscriberNote.create(subscriber: @subscriber, content: "S'est rendu sur la page 'mon financement'")
    AdminMailer.subscriber_funding_question(@subscriber.id).deliver_now
  end

  def contact_courtier_submit
    subscriber = Subscriber.find(params[:subscriber_id])
    question_category = params["question_category"]
    question_content = params["question_content"]
    SubscriberNote.create(subscriber: subscriber, content: "A posé la question suivante: '#{question_content}'")
    redirect_to subscriber_mon_financement_confirmation_path
  end

  def contact_courtier_submitted
  end


  private

  def subscriber_params
    params.require(:subscriber).permit(:firstname, :lastname, :email, :phone, :has_messenger, :facebook_id, :max_price, :min_surface, :min_rooms_number, :min_elevator_floor, :min_floor, :project_type, :additional_question, :specific_criteria, :broker_id, :status, :initial_areas, :terrace, :garden, :balcony, :new_construction, :last_floor, :min_price, :max_sqm_price)
  end
end

app/views/subscribers/activation.html.erb
<div class="row justify-content-center mt-5 mb-5">
    <img class="text-center" src="https://hellodingdong.com/assets/images/logo-ding-dong-full.png" style="height:50px" alt="Logo Ding Dong">
</div>
<div class="row">
  <div class="col-12">
  <% if !@subscriber.is_blocked %>
    <h1>Merci</h1>
    <p>
      <%= @subscriber.firstname %> <%= @subscriber.lastname %> recevra dorénavant les annonces Ding Dong ! 
      <br>Il n'a jamais été aussi près de trouver son futur bien ! 😉
    </p>
  <% else %>
    <h1>⚠️ Attention</h1>
    <p>Oups, quelque chose ne s'est pas bien passé, veuillez contacter Ding Dong svp</p>
  <% end %>
  </div>
</div>

app/views/subscribers/contact_courtier.html.erb
<div class="section bg-primary-pros" style="color: #2E60FF; font-family: 'Nunito'; font-size: 1rem;">

    <div class="container">

        <div class="row">
            <div class="col-12">
                <div class="alert alert-success" role="alert">
                    Nous avons bien noté votre demande.
                </div>
            </div>
        </div>

        <div class="row"> 
            <div class="col d-flex justify-content-center"> 
                <img src="<%= asset_path('logo_blanc.svg') %>" height="120px;">
            </div>
        </div>



        <div class="bg-white-steps" style="top: 210px !important">
            <div class="container">

                <div class="row mt-5">
                        <div class="col-12">
                        <h5>Vous souhaitez nous en dire plus ? </h5>
                        <p class="lead"><% unless @subscriber.broker.nil? %> <%= @subscriber.broker.firstname %>, notre expert en financement est là pour vous accompagner <% end %></p>
                        </div>
                        <div class="col-12">
                        <%= form_tag("/subscribers/#{@subscriber.id}/financement-submit", method: "post") do %>
                            <div class="form-group grey ">
                            <%= label_tag 'question_category', 'Catégorie'%>
                            <%= select_tag 'question_category', options_for_select(@question_categories, "1"), id:'question_category', class: 'form-control writing-box' %>
                            </div>
                            <div class="form-group grey">
                            <%= label_tag 'question_content', 'Votre question'%>
                            <%= text_area_tag 'question_content', params[:question_content], class: 'form-control writing-box', autofocus: true %>
                            </div>
                            <nav class="navbar navbar-light fixed-bottom bg-blue">
                                <div class="container justify-content-center p-0">
                                    <div class="row w-100 justify-content-center">
                                        <div class="col-12 col-md-6 col-lg-4 p-0">
                                            <%= submit_tag "Envoyer", class:"btn-outline-navbar w-100" %>
                                        </div>
                                    </div>
                                </div>
                            </nav>  
                        <% end %>
                        </div>
                    </div>
                </div>


                

            </div>
        </div>
    </div>
</div>

app/views/subscribers/edit.html.erb
<script>
$(document).ready(function(){
        var multipleCancelButton = new Choices('#choices-multiple-remove-button', {
        removeItemButton: true,
        maxItemCount:100,
        searchResultLimit:100,
        renderChoiceLimit:100
        });
    });    
</script>

<style>
    .mt-100 {
        margin-top: 100px
    }
    .choices__list--multiple .choices__item{
        background-color: #0470C1 !important;
        border-color: #0470C1 !important;
    }
</style>

<%= form_for @subscriber, url: subscriber_path(@subscriber) do |f| %>

    <nav class="navbar navbar-light fixed-bottom bg-blue d-flex justify-content-center">
        <div class="d-flex justify-content-center mt-2 mb-2">
            <%= f.submit "Enregistrer mes critères 🚀",
                         class: "btn btn-outline-light",
                         style: "font-weight:600" %>
        </div>
    </nav>  



      <h5 class="mt-4 mb-3 grey_dark">Les critères indispensables pour commencer</h6> 

      <p class="mt-4 mb-3 grey">📍 Votre zone de recherche *</p>
      <div class="raw d-flex flex-wrap">
        <div class="form-group col-12 p-0 mb-0">
            <select multiple placeholder="Ex : <%= @master_areas.first[1] + ", " + @master_areas.first[2] %> " class="form-control" id="choices-multiple-remove-button" name="areas[]">
                <% @master_areas.each do |item| %>
                    <% if item[0] == "GlobalZone"%>
                      <option value="<%= item[0] %> - <%= item[1] %>"> <%= item[1] %></option>
                    <% else %>
                      <option value="<%= item[0] %>" <%= item[3] %>> <%= item[1] + " (" + item[2] + ")" %></option>
                    <% end %>
                <% end %>
            </select>
        </div>
      </div>

    <div class="row">
        <div class="col-12 col-md-6 col-lg-4">
            <p class="mt-4 mb-3 grey">💰 Budget max *</p>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text input-group-text_style" id="basic-addon1">€</span>
                </div>
                <%= f.number_field :max_price, class: "form-control input_style", placeholder: "Ex : 500000", min: "10000", max: "10000000", :required => true %>
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
            <p class="mt-4 mb-3 grey">↔️ Surface min *</p>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text input-group-text_style" id="basic-addon1">m2</span>
                </div>
                <%= f.number_field :min_surface, type: "number", class: "form-control input_style", placeholder: "Ex : 30", min: "8", max: "400", :required => true %>
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
            <p class="mt-4 mb-3 grey">🏡 Nb. de pièces min *</p>
            <div class="input-group mb-3">
                <%= f.number_field :min_rooms_number, class: "form-control input_style", placeholder: "Ex : 1", min: "1", max: "6", :required => true %>
            </div>
        </div>
    </div>



    <h5 class="mb-2 mt-4 grey_dark">Les critères optionnels pour affiner sa recherche</h6> 

    <div class="row">
        <div class="col-12 col-md-6 col-lg-4">
            <p class="mt-4 mb-3 grey"> 💰↘️ Budget min</p>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text input-group-text_style" id="basic-addon1">€</span>
                </div>
                <%= f.number_field :min_price, class: "form-control input_style", placeholder: "Ex : 0", :required => false %>
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
            <p class="mt-4 mb-3 grey">💰↔️ Prix maximum au m2</p>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text input-group-text_style" id="basic-addon1">€ / m2</span>
                </div>
                <%= f.number_field :max_sqm_price, class: "form-control input_style", placeholder: "Ex : 12 000", :required => false %>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-6 col-lg-4">
            <p class="mt-4 mb-3 grey">🎢 Étage minimum</p>
            <div class="input-group mb-3">
                <%= f.number_field :min_floor, class: "form-control input_style", placeholder: "Ex : 1 (pas de rez-de-chaussée)", min: "0", max: "8" %>
            </div>
            <div class="form-check form-check-inline mb-3">
            <%= f.check_box :last_floor, class: "form-check-input", type:"checkbox",  id:"last_floor", value:"true" %> 
            <label class="form-check-label grey" for="last_floor">Uniquement dernier étage</label>
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
            <p class="mt-4 mb-6 grey">🚠A partir de quel étage faut-il un ascenseur</p>
            <div class="input-group mb-3" style="margin-bottom:4.5rem">
                <%= f.number_field :min_elevator_floor, class: "form-control input_style", placeholder: "Ex : 3 (ascenseur à partir du 3ème étage)", min: "0", max: "8" %>
            </div>
        </div>
    </div>
  
        <p class="mt-4 mb-6 grey">🏗️ Neuf</p>
        <div class="form-check form-check-inline">
            <%= f.check_box :new_construction, id: "new_construction", class: "form-check-input" %> 
            <%= f.label "Recevoir les constuctions neuves", for:"new_construction", class: "form-check-label grey" %> 
        </div>

        <% if false %>
        <p class="mt-4 mb-3" style="color: #0470C1; font-weight:400"> 🌻 Exterieur </p>
        <div class="form-check form-check-inline">
            <%= f.check_box :balcony, class: "form-check-input", type:"checkbox",  id:"balcony" %> 
            <label class="form-check-label" for="balcony">Balcon</label>
        </div>
        <div class="form-check form-check-inline">
            <%= f.check_box :terrace, class: "form-check-input", type:"checkbox",  id:"terrace" %> 
            <label class="form-check-label" for="terrace">Terrasse</label>
        </div>
        <div class="form-check form-check-inline">
            <%= f.check_box :garden, class: "form-check-input", type:"checkbox",  id:"garden" %> 
            <label class="form-check-label" for="garden">Jardin</label>
        </div>

        <p class="mt-4 mb-6 grey"> Souhaitez-vous une maison et/ou un appartement</p>
        <div class="form-check form-check-inline">
          <%= f.check_box :apartment_type, class: "form-check-input" %> 
          <%= f.label "Appartement", class: "form-check-label" %> 
        </div>
        <div class="form-check form-check-inline">
          <%= f.check_box :home_type, class: "form-check-input" %> 
          <%= f.label "Maison", class: "form-check-label" %> 
        </div>
        <% end %>

        <br/><br/><br/>
        <div class="d-flex justify-content-center mt-4 mb-6">
        -------- 🔔--------
        </div>
      </p>
    <% end %>
    
    

app/views/subscribers/new.html.erb
<%= simple_form_for @subscriber do |f| %>
  <%= f.error_notification %>

  <%= f.input :firstname %>
  <%= f.input :lastname %>
  <%= f.input :phone %>
  <%= f.input :email %>

  <%= f.submit 'Continue', class:"btn btn-success" %>
<% end %>

app/views/subscribers/professionals.html.erb
<div class="section bg-primary-pros">

    <div class="container">

        <div class="row"> 
            <div class="col d-flex justify-content-center"> 
                <img src="<%= asset_path('logo_blanc.svg') %>" height="120px;">
            </div>
        </div>

        <div class="mt-4" style="color:white">
            <div class="col-12">
                <h5 class="mb-3 text-center">
                    <div style="font-family: 'Nunito'"> Félicitations 🎉</div>
                    <div class="mt-2" style="font-family: 'Nunito'"> Vos critères sont enregistrés !</div>

                </h5> 
            </div>
        </div>

        <div class="bg-white-steps"  style="background: white; top: 300px !important;">
        </div>

        <div class="bg-white-steps-final-step" style="background: no-repeat center url('<%= asset_path('background-pros.svg') %>')">
        </div>

        <div class="mt-5 mb-5">
            <div class="col d-flex justify-content-center"> 
                <img src="<%= asset_path('down-arrow.svg') %>">
            </div>
        </div>

        <div class="mb-5" style="color: #2E60FF; font-family: 'Nunito'; ">
            <div class="col-12">
                <h5 class="mb-3 text-center">
                    <div> Découvrez tout de suite </div>
                    <div class="mt-2">les dernières annonces 🏡</div>
                </h5> 
            </div>
        </div>

        <div class="mb-5">
            <div class="col-12">
                <div class="d-flex justify-content-center mt-2 mb-2" style="font-family: 'Nunito'; font-size: 1.25rem">
                    <%# <div class="btn btn-outline-light"> Démarrer mon alerte 🚀</div> %>
                    <% if @subscriber.email_flux %>
                    <%= link_to "Démarrer mon alerte", subscriber_email_validation_path, class: 'btn-pros' %>
                    <% elsif @subscriber.messenger_flux %>
                    <%= link_to "Démarrer mon alerte", "https://m.me/#{ENV['BOT_LINK']}?ref=id--" + @subscriber.id.to_s, class: 'btn-pros' %>
                    <% end %>
                </div>
            </div>
        </div>

    </div>

</div>